on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
name: Build 
jobs:
  call-build-infra-steps:
    name: Build Infra
    uses: ./.github/workflows/build-infra-steps.yml
    with:
      infraPath: ./infra
      
  call-build-app-steps:
    name: Build App
    uses: ./.github/workflows/build-app-steps.yml
    with:
      solutionFolder: ./src 
