on: 
  workflow_call:
    inputs:
      infraFolder:
        required: true
        type: string
    
name: Build Infra
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@main
        
    - name: Validate Bicep File
      shell: pwsh
      run: az bicep build --file ./infra.bicep
      working-directory: ${{ inputs.infraFolder }}
        
    - name: Publish infra artifact
      uses: actions/upload-artifact@v3
      with:
        name: infra
        path: ${{ inputs.infraFolder }}
