on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
name: Build 
jobs:
  call-build-infra-steps:
    uses: ./.github/workflows/templates/build-infra-steps.yml
    with:
      infraPath: ./infra
    
