on:   
  workflow_call:
    inputs:
      solutionFolder:
        required: true
        type: string
        
      infraFolder:
        required: true
        type: string

name: Build        
jobs:
  build-infra:
    name: Build Infra
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@main
        
    - name: Validate Bicep File
      shell: pwsh
      run: az bicep build --file ./infra.bicep
      working-directory: ${{ inputs.infraFolder }}
        
    - name: Publish infra artifact
      uses: actions/upload-artifact@v3
      with:
        name: infra
        path: ${{ inputs.infraFolder }}
      
  build-app:
    name: Build App
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout code 
      uses: actions/checkout@main
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ inputs.solutionFolder }}
        
    - name: Build solution
      run: dotnet build --configuration Release --no-restore --output ./output
      working-directory: ${{ inputs.solutionFolder }}
      
    - name: Test solution
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ inputs.solutionFolder }}
     
    - name: Publish app artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ${{ inputs.solutionFolder }}/output
