on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
name: Build 
jobs:
  Build_Infra:
    runs-on: ubuntu-latest
    steps:
      - name: Build Infra
        uses: ./.github/workflows/templates/build-infra-steps.yml
        with:
          infraPath: ./infra
    
