on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
name: Build 
jobs:
  call-build-infra-steps:
    name: Build Infra
    uses: ./.github/workflows/build-infra-steps.yml
    with:
      infraPath: ./infra
      
  call-build-infra-steps2:
    name: Build Infra 2
    uses: ./.github/workflows/build-infra-steps.yml
    with:
      infraPath: ./infra  
