on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
       
name: Build 
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      infraFolder: ./infra
      solutionFolder: ./src 
    
  deploy-to-dev:
    name: Deploy to DEV
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
