on: 
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
       
name: Release 
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      infraFolder: ./infra
      solutionFolder: ./src 
    
  deploy-to-dev:
    name: Deploy to DEV
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets:
      azCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      
  deploy-to-tst:
    name: Deploy to TST
    needs: deploy-to-dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: tst
    secrets:
      azCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      
  deploy-to-prd:
    name: Deploy to PRD
    needs: deploy-to-tst
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prd
    secrets:
      azCredentials: ${{ secrets.AZURE_CREDENTIALS }}
