on:   
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      azCredentials:
        required: true
        
name: Deploy 
jobs:
  deploy-infra:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
    
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azCredentials }} 
    
    - name: Download infra artifact
      uses: actions/download-artifact@v3
      with:
        name: infra
        path: infra
        
    - name: Deploy infra with Bicep
      shell: pwsh
      run: ./_infra.ps1 -environment dev
      working-directory: ./infra

    - name: Download app artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: app
        
    - name: Deploy code to the App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: yac-${{ inputs.environment }}-bicepdemo-app
        package: ./app
