on:   
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
name: Deploy 
jobs:
  deploy-infra:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
    
    - name: Download infra artifact
      uses: actions/download-artifact@v3
      with:
        name: infra
        
    - name: Test
      shell: pwsh
      run: az version
      working-directory: ./infra
    
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
    - name: Deploy infra with Bicep
      shell: pwsh
      run: ./_infra.ps1 -environment dev
      working-directory: ./infra

    - name: Download app artifact
      uses: actions/download-artifact@v3
      with:
        name: app
