on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
name: Deploy App
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    
    - name: Download app artifact
      uses: actions/download-artifact@v3
      with:
        name: app
    
