on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
name: Deploy Infra
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Download infra artifact
      uses: actions/download-artifact@v3
      with:
        name: infra
    
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MVP_SUBSCRIPTION_CREDENTIALS }}
