on: 
  push:
    branches:
    - main
    - 'releases/**'
name: Deploy Azure Infrastructure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MVP_SUBSCRIPTION_CREDENTIALS }}


    - name: PowerShell script
      shell: pwsh
      run: ./_infra.ps1 -environment dev
      working-directory: ./infra
        
        

